version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: fc_docker_desafio_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      -  fc-docker-network
    depends_on:
      - node
      - db
  node:
    build:
      dockerfile: ./node/Dockerfile
      context: .
    container_name: fc_docker_desafio_node
    working_dir: /usr/src/app
    volumes:
      - ./node:/usr/src/app
    command: bash -c "npm i && node index.js"
    networks:
      - fc-docker-network
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: fc_docker_desafio_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fc_docker_desafio
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    networks:
      - fc-docker-network

networks:
  fc-docker-network:
    driver: bridge